### ISSUE TITLE
Training Files

### ISSUE THREAD

**Issue by ghost** [dtransposed/LSTM-model-in-C#1]
Hello,

could you upload the NN.txt and input.txt please ?

Thanks,

Pummelchen

**Comment by dtransposed** [comment]
Hello Pummelchen. It is still WIP so I did not intend to upload all the files. But no problem, here are the sample files: 
[NN.txt](https://github.com/dtransposed/LSTM-model-in-C/files/2084110/NN.txt)
[input.txt](https://github.com/dtransposed/LSTM-model-in-C/files/2084113/input.txt)
